<a href="https://colab.research.google.com/github/VASAVI1231/Dataset-Columns-Using-Pandas-loc-and-iloc/blob/main/Select_Dataset_Columns_Using_Pandas_loc_and_iloc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Task 18: Select Dataset Columns using Pandas loc and iloc

# Step 1: Import libraries
import pandas as pd
from sklearn.datasets import load_iris

# Step 2: Load Iris dataset
iris = load_iris()

# Step 3: Create DataFrame
df = pd.DataFrame(
    iris.data,
    columns=[
        "sepal_length",
        "sepal_width",
        "petal_length",
        "petal_width"
    ]
)

# Step 4: Add target/species column
df["species"] = [
    iris.target_names[i]
    for i in iris.target
]

# Display first 5 records
print("First 5 Records:")
display(df.head())

# --------------------------------------------------
# 1. Select a single column
# --------------------------------------------------

print("\n1. Single Column - Species:")
print(df["species"])


# --------------------------------------------------
# 2. Select multiple columns
# --------------------------------------------------

print("\n2. Multiple Columns:")
display(
    df[["sepal_length", "petal_length"]]
)


# --------------------------------------------------
# 3. Select rows using loc
# --------------------------------------------------

print("\n3. First 5 Rows using loc:")
display(df.loc[0:4])


# --------------------------------------------------
# 4. Select specific rows and columns using loc
# --------------------------------------------------

print("\n4. Selected Rows and Columns using loc:")
display(
    df.loc[
        0:4,
        ["sepal_length", "species"]
    ]
)


# --------------------------------------------------
# 5. Select rows using iloc
# --------------------------------------------------

print("\n5. First 5 Rows using iloc:")
display(df.iloc[0:5])


# --------------------------------------------------
# 6. Select specific rows and columns using iloc
# --------------------------------------------------

print("\n6. Selected Rows and Columns using iloc:")
display(
    df.iloc[
        0:5,
        [0, 4]
    ]
)


# --------------------------------------------------
# 7. Select a single value using loc
# --------------------------------------------------

print("\n7. Single Value using loc:")
print(df.loc[0, "species"])


# --------------------------------------------------
# 8. Select a single value using iloc
# --------------------------------------------------

print("\n8. Single Value using iloc:")
print(df.iloc[0, 4])


# --------------------------------------------------
# Final DataFrame information
# --------------------------------------------------

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
print(df.columns.tolist())

First 5 Records:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

1. Single Column - Species:
0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

2. Multiple Columns:

     sepal_length  petal_length
0             5.1           1.4
1             4.9           1.4
2             4.7           1.3
3             4.6           1.5
4             5.0           1.4
..            ...           ...
145           6.7           5.2
146           6.3           5.0
147           6.5           5.2
148           6.2           5.4
149           5.9           5.1

[150 rows x 2 columns]

3. First 5 Rows using loc:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

4. Selected Rows and Columns using loc:

   sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa

5. First 5 Rows using iloc:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

6. Selected Rows and Columns using iloc:

   sepal_length species
0           5.1  setosa
1           4.9  setosa
2           4.7  setosa
3           4.6  setosa
4           5.0  setosa

7. Single Value using loc:
setosa

8. Single Value using iloc:
setosa

Dataset Shape:
(150, 5)

Column Names:
['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']